baseURL = 'https://fedesilvaponte.github.io/fs-testing-pages'
languageCode = 'en-us'
title = 'Dualboot Partners'
theme = "hugo-book"


[params]
    BookTheme = 'dark'
    BookSearch = false
    BookComments = false
